### ISSUE TITLE
java.lang.IllegalStateException: Queue full

### ISSUE THREAD

**Issue by oneroman** [aurae/RxBonjour#19]
Sometime I am have the following crash in my app due to
`java.lang.IllegalStateException: Queue full
at java.util.AbstractQueue.add(AbstractQueue.java:69)
at rxbonjour.internal.Backlog.add(Backlog.java:75)
at rxbonjour.discovery.JBBonjourDiscovery$1$1.onServiceFound(JBBonjourDiscovery.java:115)
at android.net.nsd.NsdManager$ServiceHandler.handleMessage(NsdManager.java:333)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:145)
at android.os.HandlerThread.run(HandlerThread.java:61)
`

Can we fix it by increasing a queue from 32 to some bigger value? or any other better fixes also welcome. Thank you!

**Comment by oneroman** [comment]
It seems this could happen, if Service could not be resolved then items won't be removed from the queue at all.

**Comment by mannodermaus** [comment]
I'm changing the underlying `Queue` implementation to become self-aware, so that the head element is removed when trying to add new elements to the tail, effectively enforcing a timeout on the oldest unresolved Services. This'll be part of 1.0.1 and the next preview of 2.0.0!

**Comment by mannodermaus** [comment]
Released in the aforementioned builds. Please feel free to re-open if you still encounter this issue!
